// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gruyxphdrhodqeojltlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydXl4cGhkcmhvZHFlb2psdGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzU1OTksImV4cCI6MjA3NDY1MTU5OX0.l-upD0wNQiXICGjcNBjQuTCDQkLiOe0USAS-nmKHlgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});